-- Contacts: the owner keeps a book of contacts for each client. Each contact has a name, an email
-- and a role, and belongs to one client (client_id references client.id).
CREATE TABLE contact (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client(id),
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL
);
