-- Tasks: a checklist the owner keeps on each project. Each task belongs to exactly one project
-- (project_id FK) and can be ticked off (done). Additive: a new versioned migration.
CREATE TABLE tasks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN NOT NULL DEFAULT FALSE
);
