-- Line items: the things an invoice is charging for. Each line belongs to exactly one invoice
-- (invoice_id FK) and carries a description, a quantity (qty) and the price of each unit
-- (unit_price). An invoice's amount is the sum of each line's qty * unit_price. Additive: a new
-- versioned migration alongside the existing invoices table.
CREATE TABLE line_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoices(id),
    description VARCHAR(255) NOT NULL,
    qty         INTEGER NOT NULL,
    unit_price  NUMERIC(19, 2) NOT NULL
);
