-- Project tasks feature: a checklist item on a project (title + whether it is done).
-- BY DEFAULT identity so the test seed can insert explicit ids (fixture ids), while normal
-- creates still auto-generate. project_id is a required foreign key onto projects; done tracks
-- whether the task has been ticked off (defaults to open).
CREATE TABLE tasks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN NOT NULL DEFAULT FALSE
);
