-- Invoice line items: an invoice is now built from the things being charged for. Each line records
-- a description, a quantity, and the price of each — the invoice's amount is the sum of qty*price
-- across its lines. Additive: a new table alongside invoices, one row per line.
CREATE TABLE line_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoices(id),
    description VARCHAR(255) NOT NULL,
    qty         INTEGER NOT NULL,
    unit_price  DECIMAL(12, 2) NOT NULL
);

-- The invoice amount is no longer a single figure the user types: it is derived from the line
-- items. Relax the stored amount column so an invoice can exist (and start empty, totalling zero)
-- without a typed amount — the running total is computed from its lines.
ALTER TABLE invoices DROP CONSTRAINT invoices_amount_positive;
ALTER TABLE invoices ALTER COLUMN amount SET NULL;
ALTER TABLE invoices ALTER COLUMN amount SET DEFAULT 0;
