-- Tasks: each project keeps a checklist of tasks. Each task has a title, belongs to one project
-- (project_id references project.id) and is either OPEN (done = FALSE) or DONE (done = TRUE). The
-- project's detail screen lists its tasks and lets the owner tick them off.
CREATE TABLE task (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN NOT NULL DEFAULT FALSE
);
