-- Invoices are now built from line items rather than a single typed figure. Each line item belongs
-- to one invoice (invoice_id references invoice.id) and records what is being charged for: a
-- description, a quantity and the unit price. The invoice's amount is the sum of each line's
-- quantity times unit price. An invoice may legitimately carry no line items yet (a just-started
-- invoice whose amount is 0), so relax the V6 positivity check that forbade a zero amount; the
-- invoice.amount column stays as the maintained total of its line items.
CREATE TABLE line_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoice(id),
    description VARCHAR(255) NOT NULL,
    quantity    INT NOT NULL,
    unit_price  DECIMAL(12, 2) NOT NULL
);

ALTER TABLE invoice DROP CONSTRAINT invoice_amount_positive;
