-- Project tags feature: labels that can be attached to projects to group them.
-- BY DEFAULT identity so the test seed can insert explicit ids (fixture ids), while normal
-- creates still auto-generate. project_tags is the many-to-many join between projects and tags;
-- each (project_id, tag_id) pair appears at most once.
CREATE TABLE tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE project_tags (
    project_id BIGINT NOT NULL REFERENCES projects(id),
    tag_id     BIGINT NOT NULL REFERENCES tags(id),
    PRIMARY KEY (project_id, tag_id)
);
