-- Notes: free-text notes the owner writes on a target (currently a project). A note belongs to one
-- target (target_type + target_id) and is stamped with when it was written so the newest shows
-- first. Additive: a new versioned migration.
CREATE TABLE notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id   BIGINT NOT NULL,
    body        VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
