-- Notes feature: a free-text note written against a target (e.g. a project). Polymorphic by
-- target_type + target_id so notes can attach to any entity. BY DEFAULT identity so the test seed
-- can insert explicit fixture ids while normal creates still auto-generate. created_at is an ISO-8601
-- instant stored as text: lexicographically sortable, so "newest first" is ORDER BY created_at DESC.
CREATE TABLE notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id   BIGINT NOT NULL,
    text        VARCHAR(2000) NOT NULL,
    created_at  VARCHAR(64) NOT NULL
);
