-- Task list a user keeps on a project. Each task belongs to one project and can be ticked off.
CREATE TABLE tasks (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT       NOT NULL REFERENCES projects(id),
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN      NOT NULL DEFAULT FALSE
);
