-- Tags group projects: a tag has a name, and a project may carry any number of tags. The join table
-- project_tag links a project to a tag (both FK-referenced), one row per (project, tag) pairing. A
-- project's detail screen lists its tags as chips and lets the owner add or remove them.
CREATE TABLE tag (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE project_tag (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    tag_id     BIGINT NOT NULL REFERENCES tag(id),
    UNIQUE (project_id, tag_id)
);
