-- Notes: a free-text note written against some target (a project today; the target_type/target_id
-- pair keeps it generic for other entities later). Each note records when it was written (at) so the
-- target's detail screen can list its notes newest first. body holds the note text (TEXT is a type
-- alias in H2, so the column is named body rather than text).
CREATE TABLE note (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id   BIGINT NOT NULL,
    body        VARCHAR(2000) NOT NULL,
    at          TIMESTAMP NOT NULL
);
