-- An invoice is now itemised: instead of typing one figure, you list the things you are charging
-- for. Each line item belongs to one invoice and carries a description, a quantity and the price
-- for a single unit. The invoice's amount is the sum of each line's quantity times unit price.
CREATE TABLE line_items (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT         NOT NULL REFERENCES invoices(id),
    description VARCHAR(255)   NOT NULL,
    qty         INTEGER        NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL
);

CREATE INDEX idx_line_items_invoice_id ON line_items(invoice_id);
