-- Payments: money a client has paid against an invoice. Each payment belongs to exactly one invoice
-- (invoice_id FK) and records how much was paid (amount) and when (paid_date). An invoice can have
-- many payments. Additive: a new versioned migration alongside the existing invoices table.
CREATE TABLE payments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    amount     NUMERIC(19, 2) NOT NULL,
    paid_date  DATE NOT NULL
);
