-- Invoice payments: record what a client has paid against an invoice. Each row is one payment with
-- a money amount and the date it was paid. Additive: a new table alongside invoices, one row per
-- payment, referencing the invoice it is paid against.
CREATE TABLE payments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    amount     DECIMAL(12, 2) NOT NULL,
    paid_date  DATE NOT NULL
);
