-- Payments: what a client has actually paid against an invoice. Each payment belongs to one invoice
-- (invoice_id references invoice.id) and records how much was paid (amount) and when (paid_date).
-- An invoice's detail screen lists its payments alongside its line items.
CREATE TABLE payment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoice(id),
    amount     DECIMAL(12, 2) NOT NULL,
    paid_date  DATE NOT NULL
);
