-- Clients feature: name + email, one row per client.
-- BY DEFAULT identity so the test seed can insert explicit ids (fixture ids), while normal
-- creates still auto-generate.
CREATE TABLE clients (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
