-- Labels a user puts on projects to group them. A tag is a reusable label; a project can carry many
-- tags and a tag can be on many projects, so the two are linked through a join table.
CREATE TABLE tags (
    id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE project_tags (
    project_id BIGINT NOT NULL REFERENCES projects(id),
    tag_id     BIGINT NOT NULL REFERENCES tags(id),
    PRIMARY KEY (project_id, tag_id)
);
