-- Free-text notes a user writes about something in the app. A note is generic: it points at a
-- target by type + id (e.g. a 'project') so the same table can carry notes for other kinds later.
-- Each note records WHEN it was written so the UI can show the newest first.
CREATE TABLE notes (
    id          BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32)              NOT NULL,
    target_id   BIGINT                   NOT NULL,
    text        VARCHAR(4000)            NOT NULL,
    at          TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_notes_target ON notes (target_type, target_id);
