-- A client can pay against an invoice over time. Each payment records how much was paid and the
-- date it was paid, and belongs to exactly one invoice. Payments are shown on the invoice.
CREATE TABLE payments (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT         NOT NULL REFERENCES invoices(id),
    amount     NUMERIC(12, 2) NOT NULL,
    paid_date  DATE           NOT NULL
);

CREATE INDEX idx_payments_invoice_id ON payments(invoice_id);
