-- Client payment: a single lump sum a client pays at once, split (allocated) across several of that
-- client's open invoices. The lump is recorded here (client_id, amount, paid_date); each share of it
-- is an ordinary payment row (V19) that now also points back at the lump it came from via
-- client_payment_id. An invoice's balance is still just its billed amount minus every payment against
-- it, so allocations settle invoices through the same derived status as a single payment does.
CREATE TABLE client_payment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client(id),
    amount    DECIMAL(12, 2) NOT NULL,
    paid_date DATE NOT NULL
);

ALTER TABLE payment
    ADD COLUMN client_payment_id BIGINT NULL REFERENCES client_payment(id);
