-- Second domain table: projects a user does for a client. Each project belongs to one client.
CREATE TABLE projects (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    client_id BIGINT       NOT NULL REFERENCES clients(id)
);
