-- Projects: the owner tracks the work they do for a client. Each project has a name and belongs to
-- one client (client_id references client.id). Second domain table; joins to client for the name.
CREATE TABLE project (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    client_id BIGINT NOT NULL REFERENCES client(id)
);
