-- Projects: work the owner does for a client. Each project belongs to exactly one client
-- (client_id FK). Additive: a new versioned migration alongside the clients tables.
CREATE TABLE projects (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    client_id BIGINT NOT NULL REFERENCES clients(id)
);
