-- Third domain table: invoices raised against a project. Each invoice belongs to one project and
-- carries a money amount (two decimal places).
CREATE TABLE invoices (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT         NOT NULL REFERENCES projects(id),
    amount     NUMERIC(12, 2) NOT NULL
);
