-- Invoices feature: an invoice belongs to a project and records a money amount.
-- BY DEFAULT identity so the test seed can insert explicit ids (fixture ids), while normal
-- creates still auto-generate. project_id is a required foreign key onto projects.
CREATE TABLE invoices (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    amount     DECIMAL(12, 2) NOT NULL
);
