-- Invoices: money billed on a project. Each invoice belongs to exactly one project (project_id FK).
-- Additive: a new versioned migration alongside the clients and projects tables.
CREATE TABLE invoices (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    amount     NUMERIC(19, 2) NOT NULL
);
