-- Client contacts feature: a contact person kept for a client (name + email + role).
-- BY DEFAULT identity so the test seed can insert explicit ids (fixture ids), while normal
-- creates still auto-generate. client_id is a required foreign key onto clients.
CREATE TABLE contacts (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL
);
