-- Contacts: people to reach at a client (name, email, role). Each contact belongs to exactly one
-- client (client_id FK). Additive: a new versioned migration alongside the existing tables.
CREATE TABLE contacts (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL
);
